<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

$rutaActual = ".";
$directorio = opendir($rutaActual); //ruta actual
$rutaNombre = $_SERVER['REQUEST_URI'];
$rutaServer = $_SERVER['HTTP_HOST'];
?>

<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<head>
		<title>
			Manuel Rodríguez Camacho - Cinvestav
		</title>
	</head>
	<body>
		<div>
			<div>
				<h2 style="color: #000F5B;">
				Manuel Rodríguez Camacho
				</h2>
			<div>
			<div>
				<h3 style="color: #000F5B;">
				Índice en http://<?php echo($rutaServer . $rutaNombre); ?>
				</h3>
			<div>
<?php
$dirs = "";
$arch = "";
while ($archivo = readdir($directorio)) //obtenemos un archivo y luego otro sucesivamente
	{
	if($archivo != "." && $archivo != ".." && $archivo != "index.html" && $archivo != "index.htm" && $archivo != "index.php")
		{
		if (is_dir($archivo))//verificamos si es o no un directorio
			{
        		$dirs .= "
		<div style='display:inline-block; text-align:center;margin:10px;min-width:150px;'>
		        <a style='text-decoration:none' href='".$archivo . "' >
	        	<img style='width:40px;vertical-align:middle;' src='data:image/png;base64,AAABAAEATE4QAAEABABAEAAAFgAAACgAAABMAAAAnAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA0AAEAMgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAACIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIgAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIA
ACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAIhEAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAESIAACEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS
AAAhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAIQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAABAAAAERERERERERERERERERERERERERERERERERERER
EREQAAABAAAQAAASIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAQAAEAABIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAEAABAAASIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiEAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAAQAAEAAC
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAAiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAA
AQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAAiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAAiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAA
AiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIg
AAEAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIgAAEAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIgAAEAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQ
AAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIAABAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAAEAACIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAASIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIAABAAAQAAEiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAQAA
EAABIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAEAABAAABEiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIAABAAAQAAAAAAAAAAAAAAAAAAAAAAAAABEiIiIiIiIiIiIiIiIi
IiAAAQAAIQAAAAAAAAAAAAAAAAAAAAAAAAAAESIiIiIiIiIiIiIiIiIgAAEAACEAAAAAAAAAAAAA
AAAAAAAAAAAAAAASIiIiIiIiIiIiIiIiIAABAAAhEAAAAAAAAAAAAAAAAAAAAAAAAAAAASIiIiIi
IiIiIiIiIiAAAQAAIiEREREREREREREREREREREREREAAAESIiIiIiIiIiIiIiIgAAEAACIiIiIi
IiIiIiIiIiIiIiIiIiIiEQAAASIiIiIiIiIiIiIiIAABAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIQ
AAESIiIiIiIiIiIiIhAAAQAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAASIiIiIiIiIiIiIQAAEA
ACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAESIiIiIiIiIiIiEAABAAAiIREAAAAAAAAAAAAAAAAA
EREiIiIiIQAAESIiIiIiIiIiIQAAAQAAIhAAAAAAAAAAAAAAAAAAAAAAEiIiIiIQAAERIiIiIiIi
IhEAAAEAACIQAAAAAAAAAAAAAAAAAAAAAAEiIiIiEQAAABEREREREREAAAASAAAiEQAAAAAAAAAA
AAAAAAAAAAAAEiIiIiEQAAAAAAAAAAAAAAAAEgAAIiEAAAAAAAAAAAAAAAAAAAAAABIiIiIiEQAA
AAAAAAAAAAAAABIAACIiEQAAAAAAAAAAAAAAAAAAAAESIiIiIiERAAAAAAAAAAAAAREiAAAiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAAAAAAAAAAAEiIgAAIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
AAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAA////
////////8AAA////////////8AAA////////////8AAA////////////8AAA////////////8AAA
////////////8AAA////////////8AAA////////////8AAA////////////8AAA////////////
8AAA////////////8AAA////////////8AAAwAAAAAAAAAAAMAAAgAAAAAAAAAAAEAAAgAAAAAAA
AAAAEAAAgAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAf/////////4AAAAA//////////8AAAAA///
///////8AAAAB//////////8AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAA
B//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+
AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB///////
///+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB///
///////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAA
B//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+AAAAB//////////+
AAAAB//////////+AAAAA//////////+AAAAA//////////+AAAAA//////////+AAAAAP//////
///+AAAAAAAAAAA////+AAAAgAAAAAAP///+AAAAgAAAAAAH///+AAAAgAAAAAAD///+AAAA4AAA
AAAB///+AAAA//////8A///+AAAA///////Af//8AAAA///////gP//8AAAA///////wH//8AAAA
4AAAAA/4D//4AAAAwAAAAAf8A//wAAAAwAAAAAP8AAAAEAAAwAAAAAH+AAAAEAAA4AAAAAH/AAAA
EAAA8AAAAAH/gAAAMAAA////////8AAA8AAA////////////8AAA////////////8AAA////////
////8AAA////////////8AAA////////////8AAA////////////8AAA////////////8AAA////
////////8AAA////////////8AAA' />
        		<br>".$archivo . "</a>
        	</div>
        	"; //de ser un directorio lo envolvemos entre corchetes
			}
		else
			{
			$arch .= "
		<div style='display:inline-block; text-align:center;margin:10px;width:50px;min-width:150px;'>
		        <a style='text-decoration:none' href='".$archivo . "' >
	        	<img style='width:30px;vertical-align:middle;' src='data:image/png;base64,AAABAAEATE4QAAEABABAEAAAFgAAACgAAABMAAAAnAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAzBgUAQy8vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIAACIiIiIi
IiIiIRAAAAAAAAAAAAAAAAAAAAAAAAABEiIiIiIiIiIiAAAiIiIiIiIiEAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAASIiIiIiIiIgAAIiIiIiIiIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIiIiIiIiIA
ACIiIiIiIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIiIiIiIiAAAiIiIiIiAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABIiIiIiIgAAIiIiIiIQAAAAABEREREREREREREREREREREREQAAAAAB
IiIiIiIAACIiIiIhAAAAASIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAACIiIiIiAAAiIiIiIQAAASIi
IiIiIiIiIiIiIiIiIiIiIiIiIiEAAAASIiIiIgAAIiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiEAAAEiIiIiIAACIiIiIQAAASIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAAIiIiIiAAAiIiIi
EAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIhAAACIiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIi
AAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEA
AAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIi
IgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIi
IgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIh
AAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAi
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIi
IiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIi
IiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAA
IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAi
IiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiEAAAIi
IiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAAACIiIiIi
IiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIi
IiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAAIiIiIgAA
ACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIi
IiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIhAAACIiIiIgAA
IiIiIgAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAiIiIiIAACIiIiIAAAAiIiIiIiIiIiIi
IiIiIiIiIiIiIiIiIiEAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIQAAAC
IiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIiEAAAAAAAAAAAAAAiIiIiIAACIiIiIAAAAiIiIi
IiIiIiIiIiIiIiIQAAAAAAAAAAAAAAIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIiAAAAAAAA
AAAAAAASIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIgAAAAAAAAAAAAAAIiIiIiIAACIiIiIA
AAAiIiIiIiIiIiIiIiIiIiIAAAAAAAAAAAAAASIiIiIiAAAiIiIiAAAAIiIiIiIiIiIiIiIiIiIi
AAAAAAAAAAAAABIiIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIgAAAAAAAAAAAAEiIiIiIiIA
ACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIAAAAAAAAAAAASIiIiIiIiAAAiIiIiAAAAIiIiIiIiIiIi
IiIiIiIiAAAAAAAAAAABIiIiIiIiIgAAIiIiIgAAACIiIiIiIiIiIiIiIiIiIgAAAAAAAAAAEiIi
IiIiIiIAACIiIiIAAAAiIiIiIiIiIiIiIiIiIiIAAAAAAAAAASIiIiIiIiIiAAAiIiIiAAAAIiIi
IiIiIiIiIiIiIiIiAAAAAAAAABIiIiIiIiIiIgAAIiIiIhAAACIiIiIiIiIiIiIiIiIiIgAAAAAA
AAEiIiIiIiIiIiIAACIiIiIQAAAiIiIiIiIiIiIiIiIiIiIAAAAAAAASIiIiIiIiIiIiAAAiIiIi
EAAAEiIiIiIiIiIiIiIiIiIiAAAAAAABIiIiIiIiIiIiIgAAIiIiIiAAAAEiIiIiIiIiIiIiIiIi
IQAAAAAAEiIiIiIiIiIiIiIAACIiIiIhAAAAEiIiIiIiIiIiIiIiIiEAAAAAASIiIiIiIiIiIiIi
AAAiIiIiIgAAAAASIiIiIiIiIiIiIiIQAAAAABIiIiIiIiIiIiIiIgAAIiIiIiIQAAAAAAAAAAAA
AAAAAAAAAAAAAAEiIiIiIiIiIiIiIiIAACIiIiIiIQAAAAAAAAAAAAAAAAAAAAAAAAASIiIiIiIi
IiIiIiIiAAAiIiIiIiIQAAAAAAAAAAAAAAAAAAAAAAABIiIiIiIiIiIiIiIiIgAAIiIiIiIiIQAA
AAAAAAAAAAAAAAAAAAAAEiIiIiIiIiIiIiIiIiIAACIiIiIiIiIhAAAAAAAAAAAAAAAAAAAAEiIi
IiIiIiIiIiIiIiIiAAAiIiIiIiIiIiIREREREREREREREREREiIiIiIiIiIiIiIiIiIiIgAA////
////////8AAA//+AAAAAAB//8AAA//wAAAAAAAf/8AAA//gAAAAAAAH/8AAA//AAAAAAAAD/8AAA
/+AAAAAAAAB/8AAA/8AAAAAAAAA/8AAA/4A//////8A/8AAA/4D//////+Af8AAA/4H///////Af
8AAA/wH///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP/////
//gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP/
//////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA
/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf
8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP/////
//gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP/
//////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA
/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf
8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP///////gf8AAA/wP/////
//gf8AAA/wP///////Af8AAA/wP////4AAAf8AAA/wP////wAAAf8AAA/wP////wAAAf8AAA/wP/
///wAAA/8AAA/wP////wAAA/8AAA/wP////wAAB/8AAA/wP////wAAD/8AAA/wP////wAAH/8AAA
/wP////wAAP/8AAA/wP////wAAf/8AAA/wP////wAA//8AAA/wP////wAB//8AAA/wP////wAD//
8AAA/wP////wAH//8AAA/wH////wAP//8AAA/4D////gAf//8AAA/4B////gA///8AAA/8Af///A
B///8AAA/8AAAAAAD///8AAA/+AAAAAAH///8AAA//AAAAAAP///8AAA//gAAAAAf///8AAA//4A
AAAB////8AAA///AAAAH////8AAA' />
        		<br>".$archivo . "</a>
        	</div>
        	";
			}
		}
	}

echo("<hr />");
echo($dirs);
echo("<hr />");
echo($arch);
echo("<hr />");
?>

		</div>
	</body>
</html>
